# __BACKGROUND__
background_opacity 0.85
background_blur 1

# __FONT__
font_family      Source Code Pro
bold_font        Source Code Pro Bold
italic_font      Source Code Pro Italic
bold_italic_font Source Code Pro Bold Italic
font_size 13.0

# __COLORS__
foreground #c5c8c6
background #000000
cursor #c5c8c6
cursor_text_color #1d1f21
selection_foreground #1d1f21
selection_background #c5c8c6
active_tab_foreground   #1d1f21
active_tab_background   #c5c8c6
inactive_tab_foreground #c5c8c6
inactive_tab_background #282a2e
url_color #81a2be

# __ANSI_COLORS__
# black
color0  #1d1f21
color8  #666666

# red
color1  #cc6666
color9  #ff6b6b

# green
color2  #b5bd68
color10 #c5e478

# yellow
color3  #f0c674
color11 #f9e79f

# blue
color4  #81a2be
color12 #8ab4f8

# magenta
color5  #b294bb
color13 #c58cff

# cyan
color6  #8abeb7
color14 #8fd7d0

# white
color7  #c5c8c6
color15 #ffffff

# __SHORTCUTS__
map f11 toggle_fullscreen
